### ISSUE TITLE
Studio configuration dropdowns values

### ISSUE THREAD

**Issue by pofider** [bjrmatos/jsreport-electron-pdf#1]
Margin type and orientation are not selected after the save and reload.

![electron](https://cloud.githubusercontent.com/assets/2041960/11767341/9cb758ca-a1aa-11e5-8b8b-20fe01821114.png)

**Comment by pofider** [comment]
This is just to keep track.

It is fixed here https://github.com/jsreport/jsreport-express/issues/1

**Comment by bjrmatos** [comment]
@pofider it works for me with jsreport@0.11, it works for you?

**Comment by pofider** [comment]
Yes, this should be fine now. Closing.
