### ISSUE TITLE
add instructions to run in linux

### ISSUE THREAD

**Issue by bjrmatos** [bjrmatos/jsreport-electron-pdf#11]
based on this [comment](https://github.com/bjrmatos/electron-html-to/issues/87#issuecomment-242943527)

**Comment by julienvedebe** [comment]
Hi @bjrmatos first of all many thanks for your work I love using jsreport with electron-pdf it's awesome ! 
I need to install it on a Linux host, I have tried to follow the comment with no success, do you think you will add instructions sooner ? 

Many thanks for you help and work !

**Comment by pofider** [comment]
Something like this should work

```sh
apt-get install -y libgtk2.0-dev libxtst-dev libxss1 libgconf2-dev libnss3-dev libasound2-dev xvfb xfonts-75dpi xfonts-base

Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

export DISPLAY=:99 && node "server.js"
```

Taken from jsreport official docker image which includes this recipe

https://github.com/jsreport/jsreport/tree/master/docker/full

**Comment by julienvedebe** [comment]
Many thanks seems working i use with the command npm start --production.

Can this command be launched in background (or foreman ?) even with the Xvfb export ?

Thanks

**Comment by pofider** [comment]
I'm not a linux guy, but I guess it should work just with adding `&` at the end

```sh
export DISPLAY=:99 && npm start --production &
```

**Comment by julienvedebe** [comment]
Yes definitely it works, wander if there is a better "node" tool to run forever and proper, will try with foreman.

Thanks

**Comment by bjrmatos** [comment]
@julienvedebe hey, sorry for the delay in adding linux instructions! i promise to add instructions soon 😄 

> Yes definitely it works, wander if there is a better "node" tool to run forever and proper, will try with foreman.

you can try [PM2](http://pm2.keymetrics.io/) too, which your can configure it to start you node application in the background with predefined env vars (like  the `DISPLAY` env var)

**Comment by pofider** [comment]
Short blog post how to run jsreport using pm2 can be found here

http://jsreport.net/blog/start-jsreport-on-boot-using-pm2

**Comment by julienvedebe** [comment]
Thanks all for informations.

**Comment by bjrmatos** [comment]
closed via https://github.com/bjrmatos/jsreport-electron-pdf/pull/17
