### ISSUE TITLE
Anchor Tags

### ISSUE THREAD

**Issue by TrikinCurt** [bjrmatos/jsreport-electron-pdf#16]
<a href="http://www.cnn.com">CNN</a>

On the PDF I get both CNN with a link (Expected) but also the URL itself (http://www.cnn.com)

Am I missing something?  Is it possible to remove?  The real goal is a thumbnail image that links to a larger image.

**Comment by bjrmatos** [comment]
@TrikinCurt can you prepare a short example [here](https://playground.jsreport.net)? it would help to see if you are doing something wrong or not.

thnks

**Comment by bjrmatos** [comment]
closing since there was no response and we could not reproduce the issue.
