### ISSUE TITLE
Installation question

### ISSUE THREAD

**Issue by pofider** [bjrmatos/jsreport-electron-pdf#2]
Probably very dumb question. Why is not the `electron-prebuilt` in the `package.json` dependencies so the user don't have to install it additionally?

**Comment by bjrmatos** [comment]
well, i was thinking a lot about this when designing the package.. my main goal is to let the user to use the version of electron that he wants, only a minimal version would be require.

another motivation is that i want to let the user to use `jsreport-electron-pdf` in electron based desktop applications, so i don't want that `jsreport-electron-pdf` install `electron` inside an electron app.. in fact i'm planning to develop a `in-process` strategy to reuse the current electron process in desktop apps.

**Comment by pofider** [comment]
Fair enough, thanks for explanation.

Would be great to have a Drag And Drop designer running in Electron desktop application rendering pdf files through it. This is very important milestone for me. 

Closing this.

**Comment by bjrmatos** [comment]
in fact, i think we should do the same for `phantomjs` related packages, currently there are some packages that have `phantomjs` listed in their dependencies, so the `phantomjs` executable gets copied many times in different locations, not a big concern but maybe we can just document that `phantomjs` needs to be installed.. in the other side jsreport works best in phantomjs 1.9.8 so i see the benefits to have `phantomjs` installed automatically

> Would be great to have a Drag And Drop designer running in Electron desktop application rendering pdf files through it. This is very important milestone for me.

we're close, i will start that feature soon :+1: , just need to close some things
